import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  brain:      [{ type: 'autogenerated', dirName: 'brain' }],
  playbooks:  [{ type: 'autogenerated', dirName: 'playbooks' }],
  generators: [{ type: 'autogenerated', dirName: 'generators' }],
  prompts:    [{ type: 'autogenerated', dirName: 'prompts' }],
  templates:  [{ type: 'autogenerated', dirName: 'templates' }],
  clients:    [{ type: 'autogenerated', dirName: 'clients' }],
  cockpit:    [{ type: 'autogenerated', dirName: 'cockpit' }],
};

export default sidebars;
